1. Stwórz tablicę o nazwie `a_small_one` o wymiarach 8x8 z wartościami od 1 do 64.

2. Dla tablicy `a_small_one` policz:
   * sumę dla każdej kolumny,
   * sumę skumulowaną dla każdego wiersza,
   * wartość średnią dla każdego wiersza,

3. Zwróć podtablicę z tablicy `a_small_one` z elementami parzystymi (nie nadpisuj tej zmiennej).

4. Zapisz do zmiennej o nazwie `no_even_small_one` tablicę `a_small_one` zamieniając wartości parzyste na wartość np.nan.

5. Dla tablicy `no_even_small_one` policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):
   * sumę dla każdego wiersza,
   * średnią dla każdej kolumny,
   * wartość najmniejszą i w całej tablicy,

6. Do tablicy `no_even_small_one` wstaw za pomocą funkcji `np.where`:

   * wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję `np.isnan()`)
   * liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy `a_small_one` - dla warunku wstawiaj wartość z `a_small_one` lub `no_even_small_one`

8. Stwórz tablicę o nazwie `sto_by_sto` o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

9. Dla tablicy `sto_by_sto` policz:
   * wartość średnią w każdym wierszu i kolumnie (oddzielnie),
   * policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast).

10. Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł `timeit`) porównaj czasy wykonania dla tej tablicy:
    * zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja `savez` w dokumentacji biblioteki numpy)
    * odczytu dla trzech wyżej wymienionych plików.

In [2]:
import numpy as np

Zad 1

In [3]:
a_small_one = np.arange(1,65).reshape((8,8))
a_small_one

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

Zad 2

In [4]:
print(np.sum(a_small_one))
print(np.cumsum(a_small_one))
print(np.mean(a_small_one))

2080
[   1    3    6   10   15   21   28   36   45   55   66   78   91  105
  120  136  153  171  190  210  231  253  276  300  325  351  378  406
  435  465  496  528  561  595  630  666  703  741  780  820  861  903
  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540 1596
 1653 1711 1770 1830 1891 1953 2016 2080]
32.5


Zad 3

In [5]:
a_small_one_even = a_small_one[a_small_one % 2 == 0]
a_small_one_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])

Zad 4

In [11]:
no_even_small_one = a_small_one.astype(float)
no_even_small_one = np.where(a_small_one % 2 == 0, np.nan, a_small_one)
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

Zad 5

In [15]:
print(np.nansum(no_even_small_one, axis = 1))
print(f"MINIMUM: {np.nanmin(no_even_small_one)}")
empty_columns = np.isnan(no_even_small_one).all(axis=0)
mean_value_filtered = np.nanmean(no_even_small_one[:, ~empty_columns], axis=0)
print("Średnia dla kolumn, które nie są puste:", mean_value_filtered)


[ 16.  48.  80. 112. 144. 176. 208. 240.]
MINIMUM: 1.0
Średnia dla kolumn, które nie są puste: [29. 31. 33. 35.]


Zad 6

In [17]:
no_even_1 = np.where((~np.isnan(no_even_small_one)), no_even_small_one, 1)
no_even_1


array([[ 1.,  1.,  3.,  1.,  5.,  1.,  7.,  1.],
       [ 9.,  1., 11.,  1., 13.,  1., 15.,  1.],
       [17.,  1., 19.,  1., 21.,  1., 23.,  1.],
       [25.,  1., 27.,  1., 29.,  1., 31.,  1.],
       [33.,  1., 35.,  1., 37.,  1., 39.,  1.],
       [41.,  1., 43.,  1., 45.,  1., 47.,  1.],
       [49.,  1., 51.,  1., 53.,  1., 55.,  1.],
       [57.,  1., 59.,  1., 61.,  1., 63.,  1.]])

In [18]:
no_even_2 = np.where((a_small_one % 2 ==0), a_small_one, no_even_1)
no_even_2

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

Zad 7

In [20]:
rng = np.random.default_rng()

In [21]:
sto_by_sto = rng.standard_normal(size = (100,100))
sto_by_sto

array([[ 0.229307  ,  0.34135311,  0.76898216, ..., -0.71632867,
         0.09527631, -0.35731227],
       [-0.28731346, -0.02227383, -0.76233505, ...,  1.25761721,
         0.78852675,  1.33733301],
       [-0.16056944,  1.85589813,  0.60350699, ...,  0.58220751,
        -0.30017405,  0.04827112],
       ...,
       [-0.42950352,  1.94217968, -0.85816955, ..., -1.09549495,
         0.39565717,  0.40700167],
       [-0.19591754,  0.05409258, -0.41875757, ...,  2.10310009,
        -0.30173332,  0.6956772 ],
       [-0.71289649,  0.03144466, -0.53999308, ..., -0.69190601,
         2.59861737,  0.34994696]])

Zad 8

In [22]:
mean_columns_sto = np.mean(sto_by_sto, axis = 1)
print(f"kolumny:{mean_columns_sto}")
mean_row_sto = np.mean(sto_by_sto, axis = 0)
print(f"wiersze: {mean_row_sto}")
mean_abs_diff_rows = np.mean(np.abs(mean_row_sto - 0))
mean_abs_diff_columns = np.mean(np.abs(mean_columns_sto - 0))
print(f"Średnia różnica bezwzględna dla wierszy: {mean_abs_diff_rows}")
print(f"Średnia różnica bezwzględna dla kolumn: {mean_abs_diff_columns}")


kolumny:[-0.03239213  0.05805171 -0.05885109 -0.02671594 -0.00817661  0.18022677
  0.01726944 -0.07800809 -0.12895046 -0.14165675 -0.12153978  0.23694796
 -0.00748651  0.05455631 -0.00865294  0.07181721  0.06578523  0.07398981
 -0.04881012 -0.14992767 -0.0301277   0.06114268 -0.11589508  0.06732968
 -0.00647444 -0.00109816 -0.13872532  0.03767234  0.04950815 -0.05855445
 -0.00171276  0.10537626 -0.06063305 -0.05866838 -0.12992399 -0.05998829
  0.02087906 -0.12788831 -0.20697021 -0.0184176   0.16534605 -0.04822765
  0.07068012  0.00238398  0.11050659 -0.02635608 -0.14663338  0.11552051
 -0.08453912 -0.09096078  0.02179593  0.20536499  0.04143648  0.03524293
 -0.03885854 -0.05131251  0.07165724  0.04305287 -0.06207324 -0.09440635
 -0.08817157  0.01547748  0.09197545 -0.10666744  0.12657169 -0.1830043
  0.03822807  0.27487081  0.07982524 -0.05326691 -0.00847076  0.03495002
  0.03765367  0.03409886 -0.1105052  -0.13538827  0.02149939 -0.00285551
 -0.01013335  0.07583699  0.1595127   0.0013

ZAD 9

In [27]:
import timeit
import pickle
large_array = rng.standard_normal((1000, 1000))
print("Czas zapisu:")
print("txt:", timeit.timeit(lambda: np.savetxt("data.txt", large_array), number=10))
print("pickle:", timeit.timeit(lambda: pickle.dump(large_array, open("data.pkl", "wb")), number=10))
print("NPZ:", timeit.timeit(lambda: np.savez_compressed("data.npz", large_array), number=10))

#odczyt
print("\nCzas odczytu:")
print("txt:", timeit.timeit(lambda: np.loadtxt("data.txt"), number=10))
print("pickle:", timeit.timeit(lambda: pickle.load(open("data.pkl", "rb")), number=10))
print("NPZ:", timeit.timeit(lambda: np.load("data.npz")["arr_0"], number=10))


Czas zapisu:
txt: 10.898424499999237
pickle: 0.27336630600075296
NPZ: 4.817895517000579

Czas odczytu:
txt: 6.14567999800056
pickle: 0.02149630400163005
NPZ: 0.5628859759999614
